import { z } from "zod";

// Base schema with common fields
const TruckBaseSchema = z.object({
  truck_number: z.string().regex(/^[A-Z]{2}\d{1,2}[A-Z]{1,3}\d{1,4}$/, "Invalid truck number format"),
  // vendor_id: z.string().uuid(),
  created_at: z.date().optional(),
  updated_at: z.date().optional()
});

// Create schema (doesn't need timestamps as they're generated by Prisma)
export const CreateTruckSchema = TruckBaseSchema;

// Define the type for create
export type CreateTruck = z.infer<typeof CreateTruckSchema>;

// Update schema - all fields are optional
export const UpdateTruckSchema = TruckBaseSchema.partial();

// Define the type for update
export type UpdateTruck = z.infer<typeof UpdateTruckSchema>;

// Complete truck schema including timestamps (useful for responses)
export const TruckSchema = TruckBaseSchema.extend({
  id: z.string().uuid(),
  created_at: z.date(),
  updated_at: z.date(),
  // vendor: z.object({
  //   id: z.string(),
  //   name: z.string()
  // }).optional()
});

// Complete truck type (for TypeScript)
export type Truck = z.infer<typeof TruckSchema>;

// Search schema for truck searches
export const TruckSearchSchema = z.object({
  truck_number: z.string().optional(),
  // vendor_name: z.string().optional(),
  page: z.number().int().positive().optional().default(1),
  limit: z.number().int().positive().optional().default(10),
});

// Export search type
export type TruckSearch = z.infer<typeof TruckSearchSchema>;

// Filter schema
export const TruckFilterSchema = z.object({
  truck_number: z.string().optional(),
  // vendor_id: z.string().uuid().optional(),
  page: z.number().int().positive().optional().default(1),
  limit: z.number().int().positive().optional().default(10),
});

// Export filter type
export type TruckFilter = z.infer<typeof TruckFilterSchema>;